version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sidedoor
      POSTGRES_USER: sidedoor
      POSTGRES_PASSWORD: sidedoor_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://sidedoor:sidedoor_pass@postgres:5432/sidedoor
    depends_on:
      - redis
      - postgres
    volumes:
      - ./data:/data

  crawler:
    build: ./backend/workers
    environment:
      - REDIS_URL=redis://redis:6379
      - WORKER_ID=crawler-1
    depends_on:
      - redis
    volumes:
      - ./data:/data

volumes:
  redis_data:
  postgres_data:
